// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type UserInput struct {
	ID      string `json:"id"`
	Name    string `json:"name"`
	Destroy *bool  `json:"destroy"`
}
